name: CI Pipeline  # Name of the pipeline

on:  # When the pipeline runs
  push:  # On push to main
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  # What the pipeline does
  build:
    runs-on: ubuntu-latest  # On GitHub's server

    steps:
    - uses: actions/checkout@v3  # Check out your code
    - name: Setup .NET  # Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.304'  # Your .NET version from dotnet --version
    - name: Restore dependencies  # Restore packages
      run: dotnet restore
    - name: Build  # Build the project
      run: dotnet build --no-restore
    - name: Run the app  # Run the program (optional, for demo)
      run: dotnet run